<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="MONO-HYD-LAP-41" name="com.runner.test.TestEvents2" tests="6" failures="0" timestamp="18 May 2019 07:54:03 GMT" time="207.500" errors="1">
  <testcase name="connectESBDatabaseTest" time="207.500" classname="com.runner.test.TestEvents2">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.testBase.test.DatabaseUtil.ConnectToESBDatabase(DatabaseUtil.java:158)
at com.testBase.test.DatabaseUtil.ConnectDBandExecuteESBQuery(DatabaseUtil.java:59)
at com.utils.test.Utility.connectToEsbDatabase(Utility.java:26)
at com.runner.test.TestEvents2.connectESBDatabaseTest(TestEvents2.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- connectESBDatabaseTest -->
  <testcase name="WOPHierarchyValidationTest" time="0.000" classname="com.runner.test.TestEvents2">
    <skipped/>
  </testcase> <!-- WOPHierarchyValidationTest -->
  <testcase name="MPHierarchyValidationTest" time="0.000" classname="com.runner.test.TestEvents2">
    <skipped/>
  </testcase> <!-- MPHierarchyValidationTest -->
  <testcase name="MediatorHierarchyValidationTest" time="0.000" classname="com.runner.test.TestEvents2">
    <skipped/>
  </testcase> <!-- MediatorHierarchyValidationTest -->
  <testcase name="CMSNVFieldValidationsWithWOPTest" time="0.000" classname="com.runner.test.TestEvents2">
    <skipped/>
  </testcase> <!-- CMSNVFieldValidationsWithWOPTest -->
  <testcase name="CMSNVFieldValidationsWithMPTest" time="0.000" classname="com.runner.test.TestEvents2">
    <skipped/>
  </testcase> <!-- CMSNVFieldValidationsWithMPTest -->
</testsuite> <!-- com.runner.test.TestEvents2 -->
